import { ctx } from './app/context.js';
import { installScreenTransitions } from './app/shell.js';
import './screens/title.js';
import './screens/academy.js';
import './screens/league.js';
import './screens/team-select.js';
import './screens/draft.js';
import './screens/gauntlet.js';
import './screens/trials.js';
import './screens/tutorial.js';
import './battle-ui/controller.js';
import './battle-ui/hud.js';
import './battle-ui/fx.js';
import './battle-ui/playback.js';
import './screens/results.js';
import './screens/bestiary.js';
import './screens/settings.js';
import './input/gamepad.js';

installScreenTransitions();
ctx.routes.startInput();
ctx.routes.renderTitle();
